grafana:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.4.0
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
influxdb:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.4.0
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
telegraf:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.4.0
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
