name: logger
home: https://github.com/deis/logger
version: v2.3.1
description: In-memory log buffer used by Deis Workflow.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
details: |-
  Workflow is an open source PaaS that makes it easy to deploy and manage applications on your own
  servers. Workflow builds on Kubernetes to provide a lightweight, Heroku-inspired workflow.
