org: "deis"
pullPolicy: "IfNotPresent"
dockerTag: v2.3.0
# limits_cpu: "100m"
# limits_memory: "50Mi"
fluentd:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.2.0
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
redis:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.2.0
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
