name: workflow-manager
home: https://github.com/deis/workflow-manager
version: v2.4.0
description: "Deis Workflow Manager: Cluster First Aid"
maintainers:
  - name: Deis Team
    email: engineering@deis.com
details: |-
  Workflow is an open source PaaS that makes it easy to deploy and manage applications on your own
  servers. Workflow builds on Kubernetes to provide a lightweight, Heroku-inspired workflow.
