org: "deis"
pullPolicy: "IfNotPresent"
dockerTag: v2.2.2
# limits_cpu: "100m"
# limits_memory: "50Mi"
registry-proxy:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v1.1.0
  limits_cpu: "100m"
  limits_memory: "50Mi"
