{{- if eq .Values.global.storage "minio" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-minio
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.dockerTag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      serviceAccount: deis-minio
      containers:
        - name: deis-minio
          image: quay.io/{{.Values.org}}/minio:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
          env:
            - name: HEALTH_SERVER_PORT
              value: "8082"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9000
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          command:
            - boot
          args:
            - "server /home/minio/"
          volumeMounts:
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
      volumes:
        - name: minio-user
          secret:
            secretName: objectstorage-keyfile
{{- end }}
